### PR TITLE
Include json directories as packages

### PR DESCRIPTION
**Pull request by joshmoore**
Provide schema and example .json files on `pip install .`

### CODE REVIEW

**Comment by ambrosejcarr** [comment]
Walk me through why this is needed?

**Comment by joshmoore** [comment]
So ... I'm not exactly sure either. When I initially added `MANIFEST.in` I was seeing the behavior I expected within the single environment of `sptx-format`. With `build-starfish`, however, the JSON files were _not_ being copied. I tried a number of different `python setup.py` build targets. Without having the `schema` and `examples` packages mentioned, nothing work. I haven't compared the differing environments to see what the root cause is.

**Comment by joshmoore** [comment]
Temporarily closing to test py36/37 differences.

**Comment by joshmoore** [comment]
Indeed. Pinning to 3.6 solved this: https://github.com/joshmoore/build-starfish/commit/dcb2970307fd5363a173e636a36ae9daef650c68 Something to be aware of.

**Comment by joshmoore** [comment]
All my more recent testing has failed on Python 3.6 so I've reopened. Separate discussions with @ambrosejcarr point to needing a better solution that installing packages "/schema" and "/examples".

**Comment by joshmoore** [comment]
After looping back around again, this _may_ be solvable be using `pip install -e` everywhere *but* that _doesn't_ work with GitHub `https://...archive/master.zip` style URLs.

**Comment by joshmoore** [comment]
Differences for sdist and bdist look to also be relevant with `MANIFEST.in` only sufficing for half the cases.

**Comment by ambrosejcarr** [comment]
> After looping back around again, this may be solvable be using pip install -e everywhere but that doesn't work with GitHub https://...archive/master.zip style URLs.

Yea, this is super fragile and I would like to avoid this if possible. A lot of people have a "favored installation strategy" and blindly use it, in my experience.

**Comment by joshmoore** [comment]
Closing in favor of https://github.com/spacetx/starfish/pull/508

**Pull request closed without merging**
