### PR TITLE
ENH: hybridization_images -> primary_images

### PR DESCRIPTION
**Pull request by ambrosejcarr**
Addresses #9 , renaming hybridization_images -> primary_images.

### CODE REVIEW

**Comment by ttung** [comment]
This is ok w/ me but I think @dganguli and maybe Nick need to weigh in here.

**Review by dganguli — APPROVED** [review]
Love it. But I think this means we should think hard about how to prioritize the work to get Starfish to obey this format sooner than later. I think Experiment.primary_image is already a thing, but our example dataset experiment.jsons all still use hybridizaton_images?

this of course, is part of a larger convo about how to keep the code nsync w/ the spec.

@berl FYI

**Comment by berl** [comment]
I also love it. It's definitely the right move for this format, making it more useful in the future.  
@dganguli  is right tho- we need to get this shit locked down tight enough for people to make some SpaceTx datasets for SpaceTx based on SpaceTx docs that are actually consistent with the SpaceTx format repo and work with our SpaceTx pipeline.

**Comment by ambrosejcarr** [comment]
@berl We started the process of figuring out the dependencies yesterday and have a plan, but I listed it as a lower priority, which I think is what deep's comment is aimed to rectify. We'll definitely need to have this completed before call 2.

**Comment by ttung** [comment]
Anything stopping this from landing?

**Comment by ambrosejcarr** [comment]
An understanding about how to deal with dependencies between the repos. @joshmoore had some really interesting thoughts in slack that I'll point out in the sync this afternoon.

**Pull request merged**
